/*
 * generated by Xtext 2.27.0
 */
package com.ftn.siit.domj;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class QuestScriptRuntimeModule extends AbstractQuestScriptRuntimeModule {
}
