/*
 * generated by Xtext 2.27.0
 */
package com.ftn.siit.domj;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class QuestScriptStandaloneSetup extends QuestScriptStandaloneSetupGenerated {

	public static void doSetup() {
		new QuestScriptStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
