/*
 * generated by Xtext 2.27.0
 */
package com.ftn.siit.domj.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class QuestScriptUiModule extends AbstractQuestScriptUiModule {

	public QuestScriptUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
